### PR TITLE
Freq Reset Test case and amendment of delete fav exception message

### LINKED ISSUE #165: [PE-D] Additional changed description in error message for /deletefav
Would it be better to change the error message for /deletefav as it does not require any change description?

-------------
Labels: `severity.VeryLow` `type.FunctionalityBug`
original: neojiaern/ped#5

### PR DESCRIPTION
**Pull request by Johnson-Yee**
Fixes #165 
Addition of more JUnit Test
Improve test coverage

### CODE REVIEW

File: src/main/java/seedu/duke/logic/commands/favcommand/DeleteFavCommand.java [hunk 1]
```diff
@@ -11,7 +11,7 @@
 
     public DeleteFavCommand(String index) throws CustomException {
         if (index.isEmpty() || index.isBlank()) {
```
Comment (EthanWong2212) [inline src/main/java/seedu/duke/logic/commands/favcommand/DeleteFavCommand.java]:
```suggestion
        if (index.isBlank()) {
```
check for whether index is blank is sufficient so perhaps u can omit the isEmpty check

**Review by EthanWong2212 — APPROVED** [review]
