### PR TITLE
Fix bug and update test

### LINKED ISSUE #222: Favourite commands with "|" in description read as corrupted
Favourite commands with "|" in description read as corrupted and thus removed from txt file upon running of jar file

### PR DESCRIPTION
**Pull request by EthanWong2212**
fix #222

### CODE REVIEW

**Review by wamikamalik — APPROVED** [review]
LGTM!

File: src/main/java/seedu/duke/storage/FavStorage.java [hunk 1]
```diff
@@ -47,24 +51,38 @@ public void readFile() throws FileNotFoundException {
...
+        if (!isValidCommand(entryWords[0])) {
             isCorrupted = true;
             return;
         }
         FavList.addFav(new Fav(entryWords[0], entryWords[1]));
 
     }
 
+    /**
+     * Checks if command type is a valid command.
```
Comment (Johnson-Yee) [inline src/main/java/seedu/duke/storage/FavStorage.java]: This comment might be confusing. Could specify that it is a command that can be favourited.

File: src/main/java/seedu/duke/storage/FavStorage.java [hunk 2]
```diff
@@ -47,24 +51,38 @@ public void readFile() throws FileNotFoundException {
...
+     *
+     * @param command command from favlist.txt
```
Comment (Johnson-Yee) [inline src/main/java/seedu/duke/storage/FavStorage.java]: Could specify it as String variable

**Review by Johnson-Yee — APPROVED** [review]
