### PR TITLE
More JUnit

### LINKED ISSUE #184: Update JUnit tests to reflect changes in /route and /descfav
1) new exceptions added
2) more bus routes added
3) apply lecture concepts for unit tests and integration tests

### PR DESCRIPTION
**Pull request by wamikamalik**
Fix #184 
Increased test coverage: 
classes: 64% to 66%
lines: 61% to 65%

### CODE REVIEW

File: src/main/java/seedu/duke/logic/similaritycheck/SimilarityCheck.java [hunk 1]
```diff
@@ -21,33 +21,32 @@
...
+            for (int j = 1; j <= loc2.length(); j++) {
+                int now = Math.min(1 + Math.min(costs[j], costs[j - 1]),
+                        loc1.charAt(i - 1) == loc2.charAt(j - 1) ? before : before + 1);
+                before = costs[j];
+                costs[j] = now;
             }
         }
-        return costs[b.length()];
+        return costs[loc2.length()];
     }
```
Comment (yuxinwu99) [inline src/main/java/seedu/duke/logic/similaritycheck/SimilarityCheck.java:51]: Good job changing the variables as it makes it more readable. Might be good to add a Javadoc to further explain it.

Comment (wamikamalik) [reply src/main/java/seedu/duke/logic/similaritycheck/SimilarityCheck.java:51]: Yep! doing that in a different pull request

**Review by yuxinwu99 — APPROVED** [review]
